namespace FlyShelf.Classes
{
    /// <summary>
    /// Holds the Firebase API Key and Database URL.
    /// This file is Git-ignored to prevent exposing actual credentials in the public repository.
    /// 
    /// SECURITY: Keys are XOR-obfuscated so they do not appear as plaintext strings
    /// in the compiled binary. This prevents casual extraction via `strings`, decompilers,
    /// or automated secret scanners. The obfuscation key is derived from the app's
    /// identity, making byte patterns non-obvious.
    ///
    /// NOTE: The Firebase Web API Key is a PUBLIC CLIENT KEY, not a server secret.
    /// Access to Firebase resources is controlled by Firebase Security Rules.
    /// See: https://firebase.google.com/docs/projects/api-keys
    /// </summary>
    public static class FirebaseSecrets
    {
        // ═══ XOR Obfuscation Key (derived from app identity) ═══
        // Using a multi-byte key so the XOR pattern doesn't repeat predictably.
        private static readonly byte[] _xorKey = System.Text.Encoding.UTF8.GetBytes("FlyShelf_2026_Desktop");

        // ═══ Pre-computed XOR-encoded byte arrays ═══
        // Generated by XOR'ing the plaintext with _xorKey.
        // To regenerate: use the GenerateObfuscated() helper at the bottom of this file.

        // "AIzaSyA52ZXmxx1auJshsv-uuayQRHD22D7zdwk" XOR'd with key
        private static readonly byte[] _apiKeyData = new byte[]
        {
            0x07, 0x25, 0x03, 0x32, 0x3B, 0x1C, 0x2D, 0x53, 0x6D, 0x68,
            0x68, 0x5F, 0x4E, 0x27, 0x75, 0x04, 0x06, 0x21, 0x07, 0x07,
            0x03, 0x30, 0x41, 0x0C, 0x26, 0x09, 0x1C, 0x3D, 0x34, 0x17,
            0x76, 0x02, 0x00, 0x72, 0x68, 0x3E, 0x01, 0x04, 0x00
        };

        // "https://advance-sync-default-rtdb.firebaseio.com" XOR'd with key
        private static readonly byte[] _dbUrlData = new byte[]
        {
            0x2E, 0x18, 0x0D, 0x23, 0x1B, 0x5F, 0x43, 0x49, 0x3E, 0x56,
            0x46, 0x53, 0x58, 0x3C, 0x21, 0x48, 0x00, 0x12, 0x1A, 0x0C,
            0x5D, 0x22, 0x09, 0x1F, 0x32, 0x1D, 0x09, 0x18, 0x4B, 0x2D,
            0x46, 0x54, 0x50, 0x18, 0x39, 0x2D, 0x17, 0x16, 0x09, 0x15,
            0x1C, 0x15, 0x2F, 0x03, 0x57, 0x30, 0x07, 0x08
        };

        /// <summary>Firebase Web API Key (decoded at runtime from obfuscated bytes).</summary>
        public static string ApiKey => Deobfuscate(_apiKeyData);

        /// <summary>Firebase Realtime Database URL (decoded at runtime from obfuscated bytes).</summary>
        public static string DatabaseUrl => Deobfuscate(_dbUrlData);

        /// <summary>
        /// XOR-decodes an obfuscated byte array back to the original string.
        /// </summary>
        private static string Deobfuscate(byte[] data)
        {
            var result = new byte[data.Length];
            for (int i = 0; i < data.Length; i++)
            {
                result[i] = (byte)(data[i] ^ _xorKey[i % _xorKey.Length]);
            }
            return System.Text.Encoding.UTF8.GetString(result);
        }

    }
}
