const { withStringsXml } = require('expo/config-plugins');

/**
 * Expo config plugin: Fixes the app display name in strings.xml
 * 
 * Uses the proper withStringsXml mod (not withDangerousMod) so it runs
 * AFTER the template strings.xml is generated by Expo's prebuild pipeline.
 */
function withAppName(config) {
  const appName = config.name || 'FlyShelf';

  return withStringsXml(config, (mod) => {
    // Find and replace the app_name string resource
    const strings = mod.modResults.resources.string || [];
    const appNameEntry = strings.find(s => s.$.name === 'app_name');
    
    if (appNameEntry) {
      appNameEntry._ = appName;
    } else {
      // Add app_name if it doesn't exist
      strings.push({
        $: { name: 'app_name' },
        _: appName,
      });
    }
    
    mod.modResults.resources.string = strings;
    console.log(`[FlyShelf] ✅ App display name set to "${appName}" in strings.xml`);
    return mod;
  });
}

module.exports = withAppName;
